export { default as Course } from './course'
export { default as Exam } from './exam'
export { default as Intro } from './intro'
export { default as Rate } from './rate'
export { default as Schedule } from './schedule'
export { default as Trainee } from './trainee'
